version: "3.8"

volumes:
  database_volume:
    driver: local

networks:
  php_kek:
    driver: bridge

services:
  app:
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html/
    ports:
      - "89:89"
    networks:
      - php_kek

  base:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT-PASSWORD: KJKszpj
    ports:
      - "33069:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    networks:
      - php_kek
